### PR TITLE
feat: option "--csvDelimiter <delimiter>"

### PR DESCRIPTION
**Pull request by pgerlach**
A lot of CVS files are deliimited by `;` instead of `,`, and some softwares don't allow exporting using `,` as a separator.

This PR adds an optional `--csvDelimiter` option that can be used to specify the delimited we want. It defaults as comma.

Usage: `githubCsvTools --csvDelimiter ';' ./myFileDelimitedByColons.csv`

### CODE REVIEW

**Comment by gavinr** [comment]
Thank you. Can you please add the option to the README too?

**Comment by pgerlach** [comment]
✅

**Comment by gavinr** [comment]
Please add an example file (CSV with semicolon delimiters) into the `test/` folder, so I can fully test this. Thank you.

**Review by gavinr — APPROVED** [review]

**Comment by gavinr** [comment]
thanks!

**Review by lega05897-rgb — APPROVED** [review]

**Pull request merged**
